server:
  tomcat:
    uri-encoding: UTF-8

# jpa
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

# log
logging:
  config: file:src/main/resources-env/${spring.profiles.active}/log4j2.yml